version: '3.8'

services:
    nats-server:
        image: nats:latest
        ports:
            - 8222:8222

    gateway:
        depends_on:
            - nats-server
        build: ./gateway
        ports:
            - ${GATEWAY_PORT}:${GATEWAY_PORT}
        volumes:
            - ./gateway/src:/usr/src/app/src
        command: npm run start:dev
        environment:
            - PORT=3000
            - NATS_SERVERS=nats://nats-server:4222

    auth-microservice:
        depends_on:
            - nats-server
        build: ./auth-microservice
        volumes:
            - ./auth-microservice/src:/usr/src/app/src
        command: npm run start:dev
        environment:
            - PORT=3004
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=${AUTH_DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
